### ISSUE TITLE
dynamic run expensive CI

### ISSUE THREAD

**Issue by bxb100** [j178/pre-commit-rs#87]
Currently, we have some expensive CI checks, eg. docker. 

I want to add a dynamic run workflow like [OpenDAL](https://github.com/apache/opendal/blob/main/.github/scripts/test_behavior/plan.py).

```mermaid
stateDiagram-v2
    [*] --> Push
    [*] --> PR

	State1: Language CI
    note left of State1
      every expensive language CI can be set differently
    end note

    Push --> Determine
    PR --> Determine
    Determine --> State1
    State1 --> [*]
```

**Comment by j178** [comment]
Thanks, looks reasonable to me!
